In [1]:
%cd ../

/home/ivanstefanov/Repositories/used-cars-price-prediction

In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
%matplotlib inline

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA

In [9]:
from price_predictor.trainers import train_linear_model, train_ensamble_model

In [4]:
pd.set_option('display.max_columns', 50)

In [25]:
data = pd.read_csv('data/cars.csv')
data.dropna(inplace=True)
data

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,body_type,has_warranty,state,drivetrain,price_usd,is_exchangeable,location_region,number_of_photos,up_counter,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,universal,False,owned,all,10900.00,False,Минская обл.,9,13,False,True,True,True,False,True,False,True,True,True,16
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,universal,False,owned,all,5000.00,True,Минская обл.,12,54,False,True,False,False,True,True,False,False,False,True,83
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,suv,False,owned,all,2800.00,True,Минская обл.,4,72,False,True,False,False,False,False,False,False,True,True,151
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,sedan,False,owned,all,9999.00,True,Минская обл.,9,42,True,False,False,False,False,False,False,False,False,False,86
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,universal,False,owned,all,2134.11,True,Гомельская обл.,14,7,False,True,False,True,True,False,False,False,False,True,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38526,Chrysler,300,automatic,silver,290000,2000,gasoline,False,gasoline,3.5,sedan,False,owned,front,2750.00,True,Минская обл.,5,85,False,True,False,False,True,True,False,False,True,True,301
38527,Chrysler,PT Cruiser,mechanical,blue,321000,2004,diesel,False,diesel,2.2,hatchback,False,owned,front,4800.00,True,Брестская обл.,4,20,False,True,False,False,True,True,False,False,True,True,317
38528,Chrysler,300,automatic,blue,777957,2000,gasoline,False,gasoline,3.5,sedan,False,owned,front,4300.00,False,Минская обл.,3,63,False,True,False,False,True,True,False,False,True,True,369
38529,Chrysler,PT Cruiser,mechanical,black,20000,2001,gasoline,False,gasoline,2.0,minivan,False,owned,front,4000.00,True,Брестская обл.,7,156,False,True,False,False,False,False,False,False,False,True,490
38530,Chrysler,Voyager,automatic,silver,297729,2000,gasoline,False,gasoline,2.4,minivan,False,owned,front,3200.00,True,Минская обл.,4,73,False,False,False,False,False,False,False,False,False,True,632

In [26]:
dummies = pd.get_dummies(data)
dummies

,odometer_value,year_produced,engine_has_gas,engine_capacity,has_warranty,price_usd,is_exchangeable,number_of_photos,up_counter,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed,manufacturer_name_Acura,manufacturer_name_Alfa Romeo,manufacturer_name_Audi,manufacturer_name_BMW,manufacturer_name_Buick,...,engine_type_gasoline,body_type_cabriolet,body_type_coupe,body_type_hatchback,body_type_liftback,body_type_limousine,body_type_minibus,body_type_minivan,body_type_pickup,body_type_sedan,body_type_suv,body_type_universal,body_type_van,state_emergency,state_new,state_owned,drivetrain_all,drivetrain_front,drivetrain_rear,location_region_Брестская обл.,location_region_Витебская обл.,location_region_Гомельская обл.,location_region_Гродненская обл.,location_region_Минская обл.,location_region_Могилевская обл.
0,190000,2010,False,2.5,False,10900.00,False,9,13,False,True,True,True,False,True,False,True,True,True,16,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,0
1,290000,2002,False,3.0,False,5000.00,True,12,54,False,True,False,False,True,True,False,False,False,True,83,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,1,0
2,402000,2001,False,2.5,False,2800.00,True,4,72,False,True,False,False,False,False,False,False,True,True,151,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,1,0
3,10000,1999,False,3.0,False,9999.00,True,9,42,True,False,False,False,False,False,False,False,False,False,86,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0
4,280000,2001,False,2.5,False,2134.11,True,14,7,False,True,False,True,True,False,False,False,False,True,7,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38526,290000,2000,False,3.5,False,2750.00,True,5,85,False,True,False,False,True,True,False,False,True,True,301,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0
38527,321000,2004,False,2.2,False,4800.00,True,4,20,False,True,False,False,True,True,False,False,True,True,317,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0
38528,777957,2000,False,3.5,False,4300.00,False,3,63,False,True,False,False,True,True,False,False,True,True,369,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0
38529,20000,2001,False,2.0,False,4000.00,True,7,156,False,True,False,False,False,False,False,False,False,True,490,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0
38530,297729,2000,False,2.4,False,3200.00,True,4,73,False,False,False,False,False,False,False,False,False,True,632,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0

In [27]:
dummies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 38521 entries, 0 to 38530
Columns: 1236 entries, odometer_value to location_region_Могилевская обл.
dtypes: bool(13), float64(2), int64(5), uint8(1216)
memory usage: 47.5 MB

In [32]:
pca = PCA(n_components=20)
pca.fit(dummies)

PCA(n_components=20)

In [30]:
pca.explained_variance_ratio_

array([9.99999170e-01, 7.75077530e-07, 5.01351061e-08, 2.94390058e-09,
       1.71062644e-09, 6.19778098e-11, 4.63223283e-11, 2.32184370e-11,
       1.58143284e-11, 1.46526062e-11, 1.26323744e-11, 1.23689393e-11,
       1.18938631e-11, 1.01103492e-11, 9.69375273e-12, 8.78485061e-12,
       8.58658826e-12, 8.30604423e-12, 7.32951075e-12, 7.10649839e-12])

In [31]:
pca.singular_values_

array([2.29729105e+07, 2.02250114e+04, 5.14383667e+03, 1.24645835e+03,
       9.50153540e+02, 1.80856580e+02, 1.56354862e+02, 1.10696195e+02,
       9.13569469e+01, 8.79374038e+01, 8.16504712e+01, 8.07946177e+01,
       7.92278133e+01, 7.30464777e+01, 7.15257087e+01, 6.80900090e+01,
       6.73172739e+01, 6.62084348e+01, 6.21947454e+01, 6.12412480e+01])

In [40]:
from sklearn.pipeline import make_pipeline
from sklearn.svm import LinearSVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score

In [39]:
pipeline = make_pipeline(StandardScaler(), PCA(n_components=30), LinearSVR(C=0.01))
score = cross_val_score(pipeline, dummies.drop('price_usd', axis=1), dummies['price_usd'])
score

array([-1.02611094, -0.77678092, -1.24592273, -1.17609097, -0.96514524])

In [41]:
pipeline = make_pipeline(StandardScaler(), PCA(n_components=30), RandomForestRegressor(min_samples_leaf=3))
score = cross_val_score(pipeline, dummies.drop('price_usd', axis=1), dummies['price_usd'])
score

array([0.67512778, 0.72449068, 0.7061289 , 0.64823779, 0.59156988])

In [43]:
pipeline = make_pipeline(StandardScaler(), PCA(n_components=80), RandomForestRegressor())
score = cross_val_score(pipeline, dummies.drop('price_usd', axis=1), dummies['price_usd'], cv=3, n_jobs=3, verbose=1)
score

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:  6.4min finished

array([0.68245495, 0.63687801, 0.55619049])

In [44]:
pipeline = make_pipeline(StandardScaler(), PCA(n_components=15), RandomForestRegressor())
score = cross_val_score(pipeline, dummies.drop('price_usd', axis=1), dummies['price_usd'], cv=3, n_jobs=3, verbose=1)
score

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:  1.3min finished

array([0.68750627, 0.6394811 , 0.56555755])

In [45]:
pipeline = make_pipeline(StandardScaler(), PCA(n_components=45), RandomForestRegressor())
score = cross_val_score(pipeline, dummies.drop('price_usd', axis=1), dummies['price_usd'], cv=3, n_jobs=3, verbose=1)
score

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:  3.6min finished

array([0.69285347, 0.63630653, 0.55248673])

### PCA doesn't give us anything useful either